services:

  server:
    image: todo-backend-server
    build:
      context: .
    volumes:
      - ./:/usr/src/app 
    ports:
      - 4000:4000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis-cache:6379
  mongo:
    image: mongo
    ports:
     - "3456:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # - ./mongo-data:/data/db
      - ./answers:/answers
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  redis-cache:
    image: redis
    #overwrite the CMD.
    # command: ["redis-server","--appendonly", "yes"]
    # volumes:
      # - ./redis_data:/data
    ports:
      - "6378:6379"